eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB
  application:
    name: test-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=UTF8&amp&useSSL=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      maximum-pool-size: 100
mybatis-plus:
  type-aliases-package: com.huimin.entity
  type-enums-package: com.huimin.entity.enums
  configuration:
    map-underscore-to-camel-case: true
security:
  user:
    name: admin
    password: admin
logging:
  level:
    com.huimin.mapper: debug 
    
   
    
  
