eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8088/eureka/
server:
  port: 8081
spring:
  security:
    user:
      name: admin
      password: admin
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  redis:
    host: 192.168.235.129
    password: demo123
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 10
  mail:
    host: smtp.exmail.qq.com
    username: kefu@huimin100.cn
    password: 4ZvhyVzdgwxxAGkh
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=UTF8&amp&useSSL=true&zeroDateTimeBehavior=convertToNull
#    
#    type: com.zaxxer.hikari.HikariDataSource 
#    hikari:
#      auto-commit: false
####      maximum-pool-size: 100
####      connection-timeout: 1000
####      idle-timeout: 100000
####      isolate-internal-queries: false
####      
#####    multipart:
#      enabled: true
#     max-file-size: 3MB
#      max-request-size: 3MB
#  http:
#    application:
#      name: test-service
#    mvc:
#      favicon:
#        enabled: false
mybatis-plus:
  type-aliases-package: com.huimin.entity
  type-enums-package: com.huimin.entity.enums
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log/log4j2-dev.yaml
  
test:
  hikari:
    auto-commit: true
    maximum-pool-size: 10
    minimum-idle: 1
    connection-timeout: 1000
    idle-timeout: 100000
    isolate-internal-queries: false
  mydatasource:
    - name: default
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/mytest?characterEncoding=UTF8&amp&useSSL=true&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
    - name: datasource1
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/mytest?characterEncoding=UTF8&amp&useSSL=true&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
    - name: datasource2
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/mytest?characterEncoding=UTF8&amp&useSSL=true&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
  
